energy:
  label: Энергетика
  keywords:
    - энергетика
    - электроэнергия
    - энергоснабжение
    - генерация

digital_transformation:
  label: Цифровая трансформация
  keywords:
    - цифровизация
    - цифровая трансформация
    - информационные технологии
    - автоматизация
    - цифровой трансформации

finance:
  label: Финансы
  keywords:
    - банк
    - финансы
    - инвестиции
    - страхование

industry:
  label: Промышленность
  keywords:
    - промышленность
    - производство
    - машиностроение

